import Head from 'next/head';
import { gql, useMutation } from '@apollo/client';
import { SyntheticEvent, useState, useContext } from 'react';
import { useAuth } from 'auth/auth';

type AgencyLogin = {
  email: string;
  password: string;
};

const SignIn = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const { signIn } = useAuth();

  async function onSubmit(e: SyntheticEvent) {
    e.preventDefault();

    const payload: AgencyLogin = {
      email,
      password,
    };

    signIn(payload);
  }

  return (
    <>
      <form onSubmit={onSubmit}>
        <input
          type='text'
          name='email'
          placeholder='email'
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <input
          type='password'
          name='password'
          placeholder='password'
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <button type='submit'>Sign In</button>
      </form>
    </>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Home ::: /</h1>
        <div>
          <SignIn />
        </div>
      </main>
    </>
  );
}
