import PetFeed from '@/components/PetFeed';
import SignIn from '@/components/SignIn';

import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Home ::: /</h1>
        <div>
          <SignIn />

          <div>
            Pet Feed:
            <PetFeed />
          </div>
        </div>
      </main>
    </>
  );
}
